<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aporte_asociado extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Aporte_asociado_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    
    /*
     * Listing of aporte_asociado
     */
    function index()
    {
        if($this->acceso(4)){
            $data['_view'] = 'aporte_asociado/index';
            $this->load->view('layouts/main',$data);
        }
    }
    
    /* funcion que busca deudas de un asociado */
    function buscar_deudas()
    {
        if($this->acceso(4)){
            if($this->input->is_ajax_request()){
                $asociado_id = $this->input->post('asociado_id');
                $estado_id = 3;
                $res_deudas = $this->Aporte_asociado_model->get_aportesasociado($asociado_id, $estado_id);
                echo json_encode($res_deudas);
            }else{
                show_404();
            }
        }
    }
    /*
     * historial de aportes de un asociado
     */
    function historial($asociado_id)
    {
        if($this->acceso(6)){
            //$data['aporte'] = $this->Aporte_model->get_all_aporte();
            $this->load->model('Asociado_model');
            $data['asociado'] = $this->Asociado_model->get_asociado($asociado_id);

            $this->load->model('Tipo_aporte_model');
            $data['all_tipo_aporte'] = $this->Tipo_aporte_model->get_all_tipo_aporte();

            $this->load->model('Gestion_model');
            $data['all_gestion'] = $this->Gestion_model->get_all_gestion();
            $data['asociado_id'] = $asociado_id;

            $data['_view'] = 'aporte_asociado/historial';
            $this->load->view('layouts/main',$data);
        }
    }
    
    /* funcion que busca todos los aportes de un asociado */
    function buscar_historial()
    {
        if($this->acceso(6)){
            if($this->input->is_ajax_request()){
                $asociado_id = $this->input->post('asociado_id');
                $gestion_id = $this->input->post('gestion_id');
                $tipoaporte_id = $this->input->post('tipoaporte_id');

                $estado_id = 4;
                $res_deudas = $this->Aporte_asociado_model->get_historialaportes($asociado_id, $estado_id, $gestion_id, $tipoaporte_id);
                echo json_encode($res_deudas);
            }else{
                show_404();
            }
        }
    }
    
}