<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aporte_asociado extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Aporte_asociado_model');
    } 
    
    /*
     * Listing of aporte_asociado
     */
    function index()
    {
        //$data['aporte'] = $this->Aporte_model->get_all_aporte();
        /*$this->load->model('Tipo_aporte_model');
        $data['all_tipo_aporte'] = $this->Tipo_aporte_model->get_all_tipo_aporte();

        $this->load->model('Gestion_model');
        $data['all_gestion'] = $this->Gestion_model->get_all_gestion();
        */
        $data['_view'] = 'aporte_asociado/index';
        $this->load->view('layouts/main',$data);
    }
    
    /* funcion que busca deudas de un asociado */
    function buscar_deudas()
    {
        if($this->input->is_ajax_request()){
            $asociado_id = $this->input->post('asociado_id');
            $estado_id = 3;
            $res_deudas = $this->Aporte_asociado_model->get_aportesasociado($asociado_id, $estado_id);
            echo json_encode($res_deudas);
        }else{
            show_404();
        }
    }
    
}