<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asociado extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Asociado_model');
    } 

    /*
     * Listing of asociado
     */
    function index()
    {
        $data['asociado'] = $this->Asociado_model->get_all_asociado();
        
        $data['_view'] = 'asociado/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new asociado
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('asociado__nombre','Asociado  Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'estadocivil_id' => $this->input->post('estadocivil_id'),
				'expedido_id' => $this->input->post('expedido_id'),
				'genero_id' => $this->input->post('genero_id'),
				'asociado__nombre' => $this->input->post('asociado__nombre'),
				'sociado_apellido' => $this->input->post('sociado_apellido'),
				'asociado_fechanac' => $this->input->post('asociado_fechanac'),
				'asociado_ci' => $this->input->post('asociado_ci'),
				'asociado_ciext' => $this->input->post('asociado_ciext'),
				'asociado_codigo' => $this->input->post('asociado_codigo'),
				'asociado_direccion' => $this->input->post('asociado_direccion'),
				'asociado_telefono' => $this->input->post('asociado_telefono'),
				'asociado_celular' => $this->input->post('asociado_celular'),
				'asociado_foto' => $this->input->post('asociado_foto'),
				'asociado_email' => $this->input->post('asociado_email'),
				'asociado_login' => $this->input->post('asociado_login'),
				'asociado_clave' => $this->input->post('asociado_clave'),
				'asocadio_codactivacion' => $this->input->post('asocadio_codactivacion'),
				'asociado_fechactivacion' => $this->input->post('asociado_fechactivacion'),
            );
            
            $asociado_id = $this->Asociado_model->add_asociado($params);
            redirect('asociado/index');
        }
        else
        {
			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();

			$this->load->model('Estado_civil_model');
			$data['all_estado_civil'] = $this->Estado_civil_model->get_all_estado_civil();

			$this->load->model('Expedido_model');
			$data['all_expedido'] = $this->Expedido_model->get_all_expedido();

			$this->load->model('Genero_model');
			$data['all_genero'] = $this->Genero_model->get_all_genero();
            
            $data['_view'] = 'asociado/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a asociado
     */
    function edit($asociado_id)
    {   
        // check if the asociado exists before trying to edit it
        $data['asociado'] = $this->Asociado_model->get_asociado($asociado_id);
        
        if(isset($data['asociado']['asociado_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('asociado__nombre','Asociado  Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'estadocivil_id' => $this->input->post('estadocivil_id'),
					'expedido_id' => $this->input->post('expedido_id'),
					'genero_id' => $this->input->post('genero_id'),
					'asociado__nombre' => $this->input->post('asociado__nombre'),
					'sociado_apellido' => $this->input->post('sociado_apellido'),
					'asociado_fechanac' => $this->input->post('asociado_fechanac'),
					'asociado_ci' => $this->input->post('asociado_ci'),
					'asociado_ciext' => $this->input->post('asociado_ciext'),
					'asociado_codigo' => $this->input->post('asociado_codigo'),
					'asociado_direccion' => $this->input->post('asociado_direccion'),
					'asociado_telefono' => $this->input->post('asociado_telefono'),
					'asociado_celular' => $this->input->post('asociado_celular'),
					'asociado_foto' => $this->input->post('asociado_foto'),
					'asociado_email' => $this->input->post('asociado_email'),
					'asociado_login' => $this->input->post('asociado_login'),
					'asociado_clave' => $this->input->post('asociado_clave'),
					'asocadio_codactivacion' => $this->input->post('asocadio_codactivacion'),
					'asociado_fechactivacion' => $this->input->post('asociado_fechactivacion'),
                );

                $this->Asociado_model->update_asociado($asociado_id,$params);            
                redirect('asociado/index');
            }
            else
            {
				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

				$this->load->model('Estado_civil_model');
				$data['all_estado_civil'] = $this->Estado_civil_model->get_all_estado_civil();

				$this->load->model('Expedido_model');
				$data['all_expedido'] = $this->Expedido_model->get_all_expedido();

				$this->load->model('Genero_model');
				$data['all_genero'] = $this->Genero_model->get_all_genero();

                $data['_view'] = 'asociado/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The asociado you are trying to edit does not exist.');
    } 

    /*
     * Deleting asociado
     */
    function remove($asociado_id)
    {
        $asociado = $this->Asociado_model->get_asociado($asociado_id);

        // check if the asociado exists before trying to delete it
        if(isset($asociado['asociado_id']))
        {
            $this->Asociado_model->delete_asociado($asociado_id);
            redirect('asociado/index');
        }
        else
            show_error('The asociado you are trying to delete does not exist.');
    }
    
}
