<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estado_civil extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Estado_civil_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Listing of estado_civil
     */
    function index()
    {
        if($this->acceso(25)){
            $data['estado_civil'] = $this->Estado_civil_model->get_all_estado_civil();

            $data['_view'] = 'estado_civil/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new estado_civil
     */
    function add()
    {
        if($this->acceso(25)){
            $this->load->library('form_validation');
            $this->form_validation->set_rules('estadocivil_nombre','Nombre','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            if($this->form_validation->run())
            {
                $params = array(
                    'estadocivil_nombre' => $this->input->post('estadocivil_nombre'),
                );
                $estado_civil_id = $this->Estado_civil_model->add_estado_civil($params);
                redirect('estado_civil');
            }
            else
            {            
                $data['_view'] = 'estado_civil/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }  

    /*
     * Editing a estado_civil
     */
    function edit($estadocivil_id)
    {
        if($this->acceso(25)){
            // check if the estado_civil exists before trying to edit it
            $data['estado_civil'] = $this->Estado_civil_model->get_estado_civil($estadocivil_id);
            if(isset($data['estado_civil']['estadocivil_id']))
            {
                $this->load->library('form_validation');
                $this->form_validation->set_rules('estadocivil_nombre','Nombre','trim|required', array('required' => 'Este Campo no debe ser vacio'));
                if($this->form_validation->run())
                {
                    $params = array(
                        'estadocivil_nombre' => $this->input->post('estadocivil_nombre'),
                    );
                    $this->Estado_civil_model->update_estado_civil($estadocivil_id,$params);            
                    redirect('estado_civil');
                }
                else
                {
                    $data['_view'] = 'estado_civil/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The estado_civil you are trying to edit does not exist.');
        }
    } 

    /*
     * Deleting estado_civil
     */
    /*function remove($estadocivil_id)
    {
        $estado_civil = $this->Estado_civil_model->get_estado_civil($estadocivil_id);

        // check if the estado_civil exists before trying to delete it
        if(isset($estado_civil['estadocivil_id']))
        {
            $this->Estado_civil_model->delete_estado_civil($estadocivil_id);
            redirect('estado_civil/index');
        }
        else
            show_error('The estado_civil you are trying to delete does not exist.');
    }*/
    
}
