<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estado_civil extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Estado_civil_model');
    } 

    /*
     * Listing of estado_civil
     */
    function index()
    {
        $data['estado_civil'] = $this->Estado_civil_model->get_all_estado_civil();
        
        $data['_view'] = 'estado_civil/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new estado_civil
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('estadocivil_nombre','Estadocivil Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'estadocivil_nombre' => $this->input->post('estadocivil_nombre'),
            );
            
            $estado_civil_id = $this->Estado_civil_model->add_estado_civil($params);
            redirect('estado_civil/index');
        }
        else
        {            
            $data['_view'] = 'estado_civil/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a estado_civil
     */
    function edit($estadocivil_id)
    {   
        // check if the estado_civil exists before trying to edit it
        $data['estado_civil'] = $this->Estado_civil_model->get_estado_civil($estadocivil_id);
        
        if(isset($data['estado_civil']['estadocivil_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('estadocivil_nombre','Estadocivil Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'estadocivil_nombre' => $this->input->post('estadocivil_nombre'),
                );

                $this->Estado_civil_model->update_estado_civil($estadocivil_id,$params);            
                redirect('estado_civil/index');
            }
            else
            {
                $data['_view'] = 'estado_civil/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The estado_civil you are trying to edit does not exist.');
    } 

    /*
     * Deleting estado_civil
     */
    function remove($estadocivil_id)
    {
        $estado_civil = $this->Estado_civil_model->get_estado_civil($estadocivil_id);

        // check if the estado_civil exists before trying to delete it
        if(isset($estado_civil['estadocivil_id']))
        {
            $this->Estado_civil_model->delete_estado_civil($estadocivil_id);
            redirect('estado_civil/index');
        }
        else
            show_error('The estado_civil you are trying to delete does not exist.');
    }
    
}
