<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mesa_directiva extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mesa_directiva_model');
    } 

    /*
     * Listing of mesa_directiva
     */
    function index()
    {
        $data['mesa_directiva'] = $this->Mesa_directiva_model->get_all_mesa_directiva();
        
        $data['_view'] = 'mesa_directiva/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new mesa_directiva
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'asociado_id' => $this->input->post('asociado_id'),
				'gestion_id' => $this->input->post('gestion_id'),
				'organ_id' => $this->input->post('organ_id'),
				'estado_id' => $this->input->post('estado_id'),
				'mesadir_nombreasoc' => $this->input->post('mesadir_nombreasoc'),
            );
            
            $mesa_directiva_id = $this->Mesa_directiva_model->add_mesa_directiva($params);
            redirect('mesa_directiva/index');
        }
        else
        {
			$this->load->model('Asociado_model');
			$data['all_asociado'] = $this->Asociado_model->get_all_asociado();

			$this->load->model('Gestion_model');
			$data['all_gestion'] = $this->Gestion_model->get_all_gestion();

			$this->load->model('Organizacion_model');
			$data['all_organizacion'] = $this->Organizacion_model->get_all_organizacion();

			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();
            
            $data['_view'] = 'mesa_directiva/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a mesa_directiva
     */
    function edit($mesadir_id)
    {   
        // check if the mesa_directiva exists before trying to edit it
        $data['mesa_directiva'] = $this->Mesa_directiva_model->get_mesa_directiva($mesadir_id);
        
        if(isset($data['mesa_directiva']['mesadir_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'asociado_id' => $this->input->post('asociado_id'),
					'gestion_id' => $this->input->post('gestion_id'),
					'organ_id' => $this->input->post('organ_id'),
					'estado_id' => $this->input->post('estado_id'),
					'mesadir_nombreasoc' => $this->input->post('mesadir_nombreasoc'),
                );

                $this->Mesa_directiva_model->update_mesa_directiva($mesadir_id,$params);            
                redirect('mesa_directiva/index');
            }
            else
            {
				$this->load->model('Asociado_model');
				$data['all_asociado'] = $this->Asociado_model->get_all_asociado();

				$this->load->model('Gestion_model');
				$data['all_gestion'] = $this->Gestion_model->get_all_gestion();

				$this->load->model('Organizacion_model');
				$data['all_organizacion'] = $this->Organizacion_model->get_all_organizacion();

				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'mesa_directiva/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The mesa_directiva you are trying to edit does not exist.');
    } 

    /*
     * Deleting mesa_directiva
     */
    function remove($mesadir_id)
    {
        $mesa_directiva = $this->Mesa_directiva_model->get_mesa_directiva($mesadir_id);

        // check if the mesa_directiva exists before trying to delete it
        if(isset($mesa_directiva['mesadir_id']))
        {
            $this->Mesa_directiva_model->delete_mesa_directiva($mesadir_id);
            redirect('mesa_directiva/index');
        }
        else
            show_error('The mesa_directiva you are trying to delete does not exist.');
    }
    
}
