<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Organizacion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Organizacion_model');
    } 

    /*
     * Listing of organizacion
     */
    function index()
    {
        $data['organizacion'] = $this->Organizacion_model->get_all_organizacion();
        
        $data['_view'] = 'organizacion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new organizacion
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('organ_nombre','Organ Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'organ_nombre' => $this->input->post('organ_nombre'),
				'organ_slogan' => $this->input->post('organ_slogan'),
				'organ_direccion' => $this->input->post('organ_direccion'),
				'organ_telefono' => $this->input->post('organ_telefono'),
				'organ_imagen' => $this->input->post('organ_imagen'),
				'organ_departamento' => $this->input->post('organ_departamento'),
				'organ_zona' => $this->input->post('organ_zona'),
				'organ_ubicacion' => $this->input->post('organ_ubicacion'),
				'organ_email' => $this->input->post('organ_email'),
				'organ_latitud' => $this->input->post('organ_latitud'),
				'organ_longitud' => $this->input->post('organ_longitud'),
            );
            
            $organizacion_id = $this->Organizacion_model->add_organizacion($params);
            redirect('organizacion/index');
        }
        else
        {            
            $data['_view'] = 'organizacion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a organizacion
     */
    function edit($organ_id)
    {   
        // check if the organizacion exists before trying to edit it
        $data['organizacion'] = $this->Organizacion_model->get_organizacion($organ_id);
        
        if(isset($data['organizacion']['organ_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('organ_nombre','Organ Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'organ_nombre' => $this->input->post('organ_nombre'),
					'organ_slogan' => $this->input->post('organ_slogan'),
					'organ_direccion' => $this->input->post('organ_direccion'),
					'organ_telefono' => $this->input->post('organ_telefono'),
					'organ_imagen' => $this->input->post('organ_imagen'),
					'organ_departamento' => $this->input->post('organ_departamento'),
					'organ_zona' => $this->input->post('organ_zona'),
					'organ_ubicacion' => $this->input->post('organ_ubicacion'),
					'organ_email' => $this->input->post('organ_email'),
					'organ_latitud' => $this->input->post('organ_latitud'),
					'organ_longitud' => $this->input->post('organ_longitud'),
                );

                $this->Organizacion_model->update_organizacion($organ_id,$params);            
                redirect('organizacion/index');
            }
            else
            {
                $data['_view'] = 'organizacion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The organizacion you are trying to edit does not exist.');
    } 

    /*
     * Deleting organizacion
     */
    function remove($organ_id)
    {
        $organizacion = $this->Organizacion_model->get_organizacion($organ_id);

        // check if the organizacion exists before trying to delete it
        if(isset($organizacion['organ_id']))
        {
            $this->Organizacion_model->delete_organizacion($organ_id);
            redirect('organizacion/index');
        }
        else
            show_error('The organizacion you are trying to delete does not exist.');
    }
    
}
