<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_aporte extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_aporte_model');
    } 

    /*
     * Listing of tipo_aporte
     */
    function index()
    {
        $data['tipo_aporte'] = $this->Tipo_aporte_model->get_all_tipo_aporte();
        
        $data['_view'] = 'tipo_aporte/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_aporte
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tipoaporte_nombre','Tipoaporte Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'tipoaporte_nombre' => $this->input->post('tipoaporte_nombre'),
            );
            
            $tipo_aporte_id = $this->Tipo_aporte_model->add_tipo_aporte($params);
            redirect('tipo_aporte/index');
        }
        else
        {            
            $data['_view'] = 'tipo_aporte/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_aporte
     */
    function edit($tipoaporte_id)
    {   
        // check if the tipo_aporte exists before trying to edit it
        $data['tipo_aporte'] = $this->Tipo_aporte_model->get_tipo_aporte($tipoaporte_id);
        
        if(isset($data['tipo_aporte']['tipoaporte_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('tipoaporte_nombre','Tipoaporte Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'tipoaporte_nombre' => $this->input->post('tipoaporte_nombre'),
                );

                $this->Tipo_aporte_model->update_tipo_aporte($tipoaporte_id,$params);            
                redirect('tipo_aporte/index');
            }
            else
            {
                $data['_view'] = 'tipo_aporte/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_aporte you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_aporte
     */
    function remove($tipoaporte_id)
    {
        $tipo_aporte = $this->Tipo_aporte_model->get_tipo_aporte($tipoaporte_id);

        // check if the tipo_aporte exists before trying to delete it
        if(isset($tipo_aporte['tipoaporte_id']))
        {
            $this->Tipo_aporte_model->delete_tipo_aporte($tipoaporte_id);
            redirect('tipo_aporte/index');
        }
        else
            show_error('The tipo_aporte you are trying to delete does not exist.');
    }
    
}
