<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_reunion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_reunion_model');
    } 

    /*
     * Listing of tipo_reunion
     */
    function index()
    {
        $data['tipo_reunion'] = $this->Tipo_reunion_model->get_all_tipo_reunion();
        
        $data['_view'] = 'tipo_reunion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_reunion
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tiporeunion_nombre','Tiporeunion Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'tiporeunion_nombre' => $this->input->post('tiporeunion_nombre'),
            );
            
            $tipo_reunion_id = $this->Tipo_reunion_model->add_tipo_reunion($params);
            redirect('tipo_reunion/index');
        }
        else
        {            
            $data['_view'] = 'tipo_reunion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_reunion
     */
    function edit($tiporeunion_id)
    {   
        // check if the tipo_reunion exists before trying to edit it
        $data['tipo_reunion'] = $this->Tipo_reunion_model->get_tipo_reunion($tiporeunion_id);
        
        if(isset($data['tipo_reunion']['tiporeunion_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('tiporeunion_nombre','Tiporeunion Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'tiporeunion_nombre' => $this->input->post('tiporeunion_nombre'),
                );

                $this->Tipo_reunion_model->update_tipo_reunion($tiporeunion_id,$params);            
                redirect('tipo_reunion/index');
            }
            else
            {
                $data['_view'] = 'tipo_reunion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_reunion you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_reunion
     */
    function remove($tiporeunion_id)
    {
        $tipo_reunion = $this->Tipo_reunion_model->get_tipo_reunion($tiporeunion_id);

        // check if the tipo_reunion exists before trying to delete it
        if(isset($tipo_reunion['tiporeunion_id']))
        {
            $this->Tipo_reunion_model->delete_tipo_reunion($tiporeunion_id);
            redirect('tipo_reunion/index');
        }
        else
            show_error('The tipo_reunion you are trying to delete does not exist.');
    }
    
}
