<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_multa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_multa_model');
    } 

    /*
     * Listing of tipo_multa
     */
    function index()
    {
        $data['tipo_multa'] = $this->Tipo_multa_model->get_all_tipo_multa();
        
        $data['_view'] = 'tipo_multa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_multa
     */
    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_rules('tipomulta_nombre','Nombre','trim|required', array('required' => 'Este Campo no debe ser vacio'));
        $this->form_validation->set_rules('tipomulta_monto','Monto','trim|required', array('required' => 'Este Campo no debe ser vacio'));
        if($this->form_validation->run())
        {
            $estado_id = 1; // estado ACTIVO
            $params = array(
                'estado_id' => $estado_id,
                'tipomulta_nombre' => $this->input->post('tipomulta_nombre'),
                'tipomulta_monto' => $this->input->post('tipomulta_monto'),
            );
            $tipo_multa_id = $this->Tipo_multa_model->add_tipo_multa($params);
            redirect('tipo_multa');
        }
        else
        {
            $data['_view'] = 'tipo_multa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_multa
     */
    function edit($tipomulta_id)
    {   
        // check if the tipo_multa exists before trying to edit it
        $data['tipo_multa'] = $this->Tipo_multa_model->get_tipo_multa($tipomulta_id);
        if(isset($data['tipo_multa']['tipomulta_id']))
        {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('tipomulta_nombre','Nombre','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            $this->form_validation->set_rules('tipomulta_monto','Monto','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            if($this->form_validation->run())     
            {   
                $params = array(
                    'estado_id' => $this->input->post('estado_id'),
                    'tipomulta_nombre' => $this->input->post('tipomulta_nombre'),
                    'tipomulta_monto' => $this->input->post('tipomulta_monto'),
                );
                $this->Tipo_multa_model->update_tipo_multa($tipomulta_id,$params);            
                redirect('tipo_multa');
            }else{
                $this->load->model('Estado_model');
                $tipo = 1;
                $data['all_estado'] = $this->Estado_model->get_all_estadotipo($tipo);
                $data['_view'] = 'tipo_multa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('El tipo de multa que intentas modificar no existe!.');
    } 

    /*
     * Deleting tipo_multa
     */
    function remove($tipomulta_id)
    {
        $tipo_multa = $this->Tipo_multa_model->get_tipo_multa($tipomulta_id);

        // check if the tipo_multa exists before trying to delete it
        if(isset($tipo_multa['tipomulta_id']))
        {
            $this->Tipo_multa_model->delete_tipo_multa($tipomulta_id);
            redirect('tipo_multa/index');
        }
        else
            show_error('El tipo de multa que intentas eliminar no existe!.');
    }
    
}
