<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aporte_asociado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * function to add new aporte_asociado
     */
    function add_aporte_asociado($params)
    {
        $this->db->insert('aporte_asociado',$params);
        return $this->db->insert_id();
    }
}
