<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asociado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asociado by asociado_id
     */
    function get_asociado($asociado_id)
    {
        return $this->db->get_where('asociado',array('asociado_id'=>$asociado_id))->row_array();
    }
        
    /*
     * Get all asociado
     */
    function get_all_asociado($filtro)
    {
        $this->db->select('a.*, ec.estadocivil_nombre, ex.expedido_nombre, e.estado_nombre, e.estado_color, g.genero_nombre');
        $this->db->from('asociado as a');
        $this->db->join('estado_civil as ec','a.estadocivil_id = ec.estadocivil_id');
        $this->db->join('expedido as ex','a.expedido_id = ex.expedido_id');
        $this->db->join('estado as e','a.estado_id = e.estado_id');
        $this->db->join('genero as g','a.genero_id = g.genero_id');
        $this->db->order_by('a.asociado_apellido asc, a.asociado_nombre asc');
        return $this->db->get()->result_array();
        
        
        /*
        SELECT
                d.*, e.*, g.*, ec.*

            FROM
                docente d, estado e, genero g, estado_civil ec

            WHERE
                d.estado_id=e.estado_id
                and d.genero_id=g.genero_id
                and d.estadocivil_id=ec.estadocivil_id
                and (d.docente_nombre like '%".$filtro."%'
                or d.docente_apellidos like '%".$filtro."%')
                    
            ORDER BY d.docente_apellidos, d.docente_nombre
                */
        
        
    }
        
    /*
     * function to add new asociado
     */
    function add_asociado($params)
    {
        $this->db->insert('asociado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asociado
     */
    function update_asociado($asociado_id,$params)
    {
        $this->db->where('asociado_id',$asociado_id);
        return $this->db->update('asociado',$params);
    }
    
    /*
     * function to delete asociado
     */
    function delete_asociado($asociado_id)
    {
        return $this->db->delete('asociado',array('asociado_id'=>$asociado_id));
    }
}
