<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asociado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asociado by asociado_id
     */
    function get_asociado($asociado_id)
    {
        return $this->db->get_where('asociado',array('asociado_id'=>$asociado_id))->row_array();
    }
        
    /*
     * Get all asociado
     */
    function get_all_asociado()
    {
        $this->db->order_by('asociado_id', 'desc');
        return $this->db->get('asociado')->result_array();
    }
        
    /*
     * function to add new asociado
     */
    function add_asociado($params)
    {
        $this->db->insert('asociado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asociado
     */
    function update_asociado($asociado_id,$params)
    {
        $this->db->where('asociado_id',$asociado_id);
        return $this->db->update('asociado',$params);
    }
    
    /*
     * function to delete asociado
     */
    function delete_asociado($asociado_id)
    {
        return $this->db->delete('asociado',array('asociado_id'=>$asociado_id));
    }
}
