<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Configuracion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }    
    /*
     * Get configuracion by config_id
     */
    function get_configuracion($config_id)
    {
        $this->db->select('c.*, m.moneda_nombre');
        $this->db->where('c.config_id', $config_id);
        $this->db->join('moneda as m','c.moneda_id = m.moneda_id', 'left');
        return $this->db->get("configuracion as c")->row_array();
    }
        
    /*
     * Get all configuracions
     */
    function get_all_configuracion()
    {
        $this->db->order_by('config_id', 'asc');
        return $this->db->get('configuracion')->result_array();
    }
        
    /*
     * function to add new configuracion
     */
    function add_configuracion($params)
    {
        $this->db->insert('configuracion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update configuracion
     */
    function update_configuracion($config_id,$params)
    {
        $this->db->where('config_id',$config_id);
        return $this->db->update('configuracion',$params);
    }
    
    /*
     * function to delete configuracion
     */
    function delete_configuracion($config_id)
    {
        return $this->db->delete('configuracion',array('config_id'=>$config_id));
    }
    
}
