<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Genero_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get genero by genero_id
     */
    function get_genero($genero_id)
    {
        return $this->db->get_where('genero',array('genero_id'=>$genero_id))->row_array();
    }
        
    /*
     * Get all genero
     */
    function get_all_genero()
    {
        $this->db->order_by('genero_id', 'desc');
        return $this->db->get('genero')->result_array();
    }
        
    /*
     * function to add new genero
     */
    function add_genero($params)
    {
        $this->db->insert('genero',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update genero
     */
    function update_genero($genero_id,$params)
    {
        $this->db->where('genero_id',$genero_id);
        return $this->db->update('genero',$params);
    }
    
    /*
     * function to delete genero
     */
    function delete_genero($genero_id)
    {
        return $this->db->delete('genero',array('genero_id'=>$genero_id));
    }
}
