<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reunion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reunion by reunion_id
     */
    function get_reunion($reunion_id)
    {
        return $this->db->get_where('reunion',array('reunion_id'=>$reunion_id))->row_array();
    }
        
    /*
     * Get all reunion
     */
    function get_all_reunion()
    {
        $this->db->order_by('reunion_id', 'desc');
        return $this->db->get('reunion')->result_array();
    }
        
    /*
     * function to add new reunion
     */
    function add_reunion($params)
    {
        $this->db->insert('reunion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reunion
     */
    function update_reunion($reunion_id,$params)
    {
        $this->db->where('reunion_id',$reunion_id);
        return $this->db->update('reunion',$params);
    }
    
    /*
     * function to delete reunion
     */
    /*function delete_reunion($reunion_id)
    {
        return $this->db->delete('reunion',array('reunion_id'=>$reunion_id));
    }*/
    /*
     * Obtiene las reuniones dado un filtro y una gestion
     */
    function get_las_reunion($filtro, $gestion_id, $tiporeunion_id)
    {
        $comp = " ";
        if($gestion_id > 0){
            $comp = $comp." and r.gestion_id = ".$gestion_id;
        }
        if($tiporeunion_id > 0){
            $comp = $comp." and r.tiporeunion_id = ".$tiporeunion_id;
        }
        $sql = "SELECT
                 r.*, g.gestion_nombre, tr.tiporeunion_nombre, e.estado_nombre, e.estado_color
              FROM
              reunion as r
              LEFT JOIN tipo_reunion as tr on r.tiporeunion_id = tr.tiporeunion_id
              LEFT JOIN gestion as g on r.gestion_id = g.gestion_id
              LEFT JOIN estado e on r.estado_id = e.estado_id
              WHERE
                   (tr.tiporeunion_nombre like '%".$filtro."%')
                   ".$comp."
              ORDER By r.reunion_id asc";

        $reunion = $this->db->query($sql)->result_array();
        return $reunion;
    }
    /*
     * Get reunion by reunion_id mas completo
     */
    function get_lareunion($reunion_id)
    {
        $this->db->select('r.*, g.gestion_nombre, tr.tiporeunion_nombre, e.estado_nombre, e.estado_color');
        $this->db->from('reunion as r');
        $this->db->join('tipo_reunion as tr','r.tiporeunion_id = tr.tiporeunion_id', 'left');
        $this->db->join('gestion as g','r.gestion_id = g.gestion_id', 'left');
        $this->db->join('estado as e','r.estado_id = e.estado_id', 'left');
        $this->db->where('r.reunion_id',$reunion_id);
        return $this->db->get()->row_array();
    }
}
