<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reunion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reunion by reunion_id
     */
    function get_reunion($reunion_id)
    {
        return $this->db->get_where('reunion',array('reunion_id'=>$reunion_id))->row_array();
    }
        
    /*
     * Get all reunion
     */
    function get_all_reunion()
    {
        $this->db->order_by('reunion_id', 'desc');
        return $this->db->get('reunion')->result_array();
    }
        
    /*
     * function to add new reunion
     */
    function add_reunion($params)
    {
        $this->db->insert('reunion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reunion
     */
    function update_reunion($reunion_id,$params)
    {
        $this->db->where('reunion_id',$reunion_id);
        return $this->db->update('reunion',$params);
    }
    
    /*
     * function to delete reunion
     */
    function delete_reunion($reunion_id)
    {
        return $this->db->delete('reunion',array('reunion_id'=>$reunion_id));
    }
}
