<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_reunion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_reunion by tiporeunion_id
     */
    function get_tipo_reunion($tiporeunion_id)
    {
        return $this->db->get_where('tipo_reunion',array('tiporeunion_id'=>$tiporeunion_id))->row_array();
    }
        
    /*
     * Get all tipo_reunion
     */
    function get_all_tipo_reunion()
    {
        $this->db->order_by('tiporeunion_id', 'desc');
        return $this->db->get('tipo_reunion')->result_array();
    }
        
    /*
     * function to add new tipo_reunion
     */
    function add_tipo_reunion($params)
    {
        $this->db->insert('tipo_reunion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_reunion
     */
    function update_tipo_reunion($tiporeunion_id,$params)
    {
        $this->db->where('tiporeunion_id',$tiporeunion_id);
        return $this->db->update('tipo_reunion',$params);
    }
    
    /*
     * function to delete tipo_reunion
     */
    function delete_tipo_reunion($tiporeunion_id)
    {
        return $this->db->delete('tipo_reunion',array('tiporeunion_id'=>$tiporeunion_id));
    }
}
