<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_usuario by tipousuario_id
     */
    function get_tipo_usuario($tipousuario_id)
    {
        return $this->db->get_where('tipo_usuario',array('tipousuario_id'=>$tipousuario_id))->row_array();
    }
        
    /*
     * Get all tipo_usuario
     */
    function get_all_tipo_usuario()
    {
        $this->db->order_by('tipousuario_id', 'desc');
        return $this->db->get('tipo_usuario')->result_array();
    }
        
    /*
     * function to add new tipo_usuario
     */
    function add_tipo_usuario($params)
    {
        $this->db->insert('tipo_usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_usuario
     */
    function update_tipo_usuario($tipousuario_id,$params)
    {
        $this->db->where('tipousuario_id',$tipousuario_id);
        return $this->db->update('tipo_usuario',$params);
    }
    
    /*
     * function to delete tipo_usuario
     */
    function delete_tipo_usuario($tipousuario_id)
    {
        return $this->db->delete('tipo_usuario',array('tipousuario_id'=>$tipousuario_id));
    }
}
