<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
   
class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by usuario_id
     */
    function get_usuario($usuario_id)
    {
        return $this->db->get_where('usuario',array('usuario_id'=>$usuario_id))->row_array();
    }
    
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($usuario_id,$params)
    {
        $this->db->where('usuario_id',$usuario_id);
        return $this->db->update('usuario',$params);
    }
    public function yahay_login($login)
    {
        $this->db->select('usuario_id');
        $this->db->from('usuario');
        $this->db->where('usuario_login', $login);
        $query = $this->db->get();
        if ( $query->num_rows() > 0 ){
            return 1; // si hay
        } else {
            return 0; // no hay
        }
    }
    /* verifica si hay login al modificar*/
    public function yahay_loginedit($usuario_id, $login)
    {
        $this->db->select('usuario_id');
        $this->db->from('usuario');
        $this->db->where('usuario_id !=', $usuario_id);
        $this->db->where('usuario_login', $login);
        $query = $this->db->get();
        if ( $query->num_rows() > 0 ){
            return 1; // si hay
        } else {
            return 0; // no hay
        }
    }
    /*
     * Get all usuario
     */
    function get_all_usuario($filtro)
    {
        $this->db->select('u.*, e.estado_nombre, e.estado_color, tu.tipousuario_nombre');
        $this->db->from('usuario as u');
        $this->db->join('tipo_usuario as tu','u.tipousuario_id = u.tipousuario_id', 'left');
        $this->db->join('estado as e','u.estado_id = e.estado_id', 'left');
        $this->db->like('u.usuario_nombre', $filtro);
        $this->db->or_like('u.usuario_email', $filtro);
        $this->db->or_like('u.usuario_login', $filtro);
        $this->db->or_like('tu.tipousuario_nombre', $filtro);
        $this->db->group_by("u.usuario_id");
        $this->db->order_by('u.usuario_nombre asc');
        return $this->db->get()->result_array();
    }
}
